### PR TITLE
Universal Bundle

### PR DESCRIPTION
**Pull request by bh2smith**
Some projects have been struggling to import from this package because of some node target stuff I do not understand. 

Example project: https://github.com/bh2smith/nearly-safe/pull/1

```
/nearly-safe/node_modules/near-ca/dist/index.js:1
export * from "./chains/ethereum";
^^^^^^

SyntaxError: Unexpected token 'export'
```

I have tried to repackage the project and locally tested with `npm link`. Will publish a beta release from this branch and proceed.

cc @nlordell

Note that somehow also this change wound up formatting from previously unformulated files.

### CODE REVIEW

**Review by nlordell — COMMENTED** [review]
I think CommonJS is kind of old school. I expect you just need to make your other project `type: module` in order to get things to work.

**Comment by nlordell** [comment]
I looked at how some other projects do it, and some include both ES and CommonJS `dist` files and have entries in the package.json for this: https://nodejs.org/api/packages.html#conditional-exports

The aforementioned link explicitly provides a way to support both files for use with `require` and with `import`:

```js
// package.json
{
  "exports": {
    "import": "./index-module.js",
    "require": "./index-require.cjs"
  },
  "type": "module"
}
```

This probably requires two TS build steps, but that shouldn't be a big deal (and don't forget you can "inherit" ts config files for each module system you want to support).

**Comment by bh2smith** [comment]
That's great news I'll have to look into it. However I don't believe there is any reason why this project or anyone wants to support JS "require" imports if that's what all this is about. These conflicting imports have only ever come up in typescript projects. 

Note that I don't know what the changes proposed here actually mean but I am beginning to interpret it as "CommonJS" is somehow related to the import syntax convention. Up until now I was thinking these changes would make the package more universally compatible - but it doesn't need to be compatible with old JavaScript by any means.

**Comment by nlordell** [comment]
So the issue is that your TypeScript setup is generating JavaScript code with `require`s in them (i.e. "old" JavaScript, or CommonJS). This was my point about:

> I think CommonJS is kind of old school

You are basically changing this project to use the "old school" way of requiring module dependencies instead of ES modules.

The above link describes how you can support *both*, so it would be providing more compatibility.

**Comment by bh2smith** [comment]
This problem is still very prevalent causing issues with transformation of near-safe into an npm package:
https://github.com/Mintbase/near-safe/pull/23 

In fact, there are no issues with this for build it only becomes a problem when trying to run the script file.

**Comment by bh2smith** [comment]
Ok - Finally got something compatible thanks to the help of @jfschwarz and his amazing suggestion to use https://github.com/privatenumber/tsx!

**Pull request merged**
